name: Build and Deploy to Vercel (dev)

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma
        run: npm run prisma:generate

      - name: Test
        run: npm run test:unit
